MOOD_WEIGHT = 50
ARTIST_WEIGHT = 30
GENRE_WEIGHT = 20
LIKED_BONUS = 40
SKIPPED_PENALTY = -30
NEW_SONG_BONUS = 10
DIVERSITY_BONUS = 5

CONFIG = {
    "MOOD_WEIGHT": MOOD_WEIGHT,
    "ARTIST_WEIGHT": ARTIST_WEIGHT,
    "GENRE_WEIGHT": GENRE_WEIGHT,
    "LIKED_BONUS": LIKED_BONUS,
    "SKIPPED_PENALTY": SKIPPED_PENALTY,
    "NEW_SONG_BONUS": NEW_SONG_BONUS,
    "DIVERSITY_BONUS": DIVERSITY_BONUS,
    "MAX_SONGS_PER_MIX": 20,
    "SIMILARITY_THRESHOLD": 0.7
}